version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fusionpact
      POSTGRES_PASSWORD: fusionpact123
      POSTGRES_DB: fusiondb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
