name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint import
        run: |
          python - <<'PY'
import importlib
import sys
mods = ["fastapi", "uvicorn", "prometheus_fastapi_instrumentator"]
missing = []
for m in mods:
    try:
        importlib.import_module(m)
    except Exception:
        missing.append(m)
if missing:
    print("Missing:", missing)
    sys.exit(1)
print("All deps present")
PY
      - name: Build backend image
        run: docker build -t backend:test ./backend

  docker-build:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          docker build -t frontend:test ./frontend
          docker compose version || true
          docker build -t backend:test ./backend


